[tool.poetry]
name = "mangareader"
version = "0.1.0"
description = ""
authors = ["Zefirchiky <mudruk.arte@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.12,<3.13"
bs4 = "^0.0.2"
pyinstaller = "^6.10.0"
ruff = "^0.6.8"
pyside6 = "^6.7.3"
requests = "^2.32.3"
pillow = "^10.4.0"
imageio = "^2.36.0"
pyglm = "^2.7.3"
webp = "^0.4.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
