name: Versioning

on:
  release:
    tags:
      - v*

jobs:
  versioning:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Set version
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV